/**
 * Metro resolves an image import to an entry in the asset registry, which React Native's
 * `ImageSourcePropType` accepts as a number.
 *
 * Declared here rather than relying on `expo-env.d.ts`: that file is generated by the Expo CLI and
 * gitignored, so it does not exist on a clean checkout and CI would fail to typecheck any module
 * that imports an asset. Expo's own `global.d.ts` declares CSS modules but no image formats, so
 * this does not collide with it.
 */
declare module '*.png' {
  const asset: number;
  export default asset;
}
