import { z } from 'zod';

import { IsoDateTimeSchema, UuidSchema } from './identity.js';

// apps/api/prisma/schema.prisma's M7 enums (added in the persistence slice). Declared here from
// the same values rather than imported from `@nido/domain-types`, following occurrences.ts's
// precedent for enums that package does not export.
const DEVICE_PLATFORMS = ['ANDROID', 'WEB'] as const;
const NOTIFICATION_CHANNELS = ['EXPO', 'WEB_PUSH'] as const;
const NOTIFICATION_DELIVERY_STATUSES = [
  'PENDING',
  'SENDING',
  'SENT',
  'FAILED',
  'CANCELLED',
] as const;

export const DevicePlatformSchema = z.enum(DEVICE_PLATFORMS);
export const NotificationChannelSchema = z.enum(NOTIFICATION_CHANNELS);
export const NotificationDeliveryStatusSchema = z.enum(NOTIFICATION_DELIVERY_STATUSES);

// The installation id is generated by the client and persisted in expo-secure-store (native) or
// localStorage (web). It survives provider-token rotation and re-login, which is what makes
// re-registration an update instead of a new row (ADR 0012).
export const InstallationIdSchema = UuidSchema;

// `ExponentPushToken[...]` is the current shape and `ExpoPushToken[...]` the legacy one; both are
// accepted because the value is opaque to us — we only reject shapes that clearly are not a push
// token, so a malformed client never reaches the provider adapter.
export const ExpoPushTokenSchema = z
  .string()
  .trim()
  .max(255)
  .regex(/^Expo(nent)?PushToken\[[^[\]\s]+\]$/);

// Web Push keys are base64url per RFC 8291: `p256dh` is a 65-byte uncompressed P-256 point and
// `auth` a 16-byte secret, but browsers differ on whether they pad, so the charset and a generous
// length bound are validated instead of an exact size.
const WebPushKeySchema = z
  .string()
  .trim()
  .min(16)
  .max(255)
  .regex(/^[A-Za-z0-9_-]+={0,2}$/);

// A credential is a capability: whoever holds it can push to that device. It is therefore accepted
// only on the way in and never appears in a response type (see DeviceInstallationSchema).
export const ExpoCredentialSchema = z.strictObject({
  kind: z.literal('EXPO'),
  token: ExpoPushTokenSchema,
});

export const WebPushCredentialSchema = z.strictObject({
  kind: z.literal('WEB_PUSH'),
  // HTTPS only: a push service endpoint is always https, and allowing http would let a
  // misconfigured client hand the subscription to a plaintext host.
  endpoint: z.url({ protocol: /^https$/, hostname: z.regexes.domain }).max(2048),
  keys: z.strictObject({
    p256dh: WebPushKeySchema,
    auth: WebPushKeySchema,
  }),
});

export const DeviceCredentialSchema = z.discriminatedUnion('kind', [
  ExpoCredentialSchema,
  WebPushCredentialSchema,
]);

// `platform` and the credential's `kind` are not independent: Expo Push is how the Android build
// receives notifications and Web Push is how the PWA does. Encoding it here means the API never
// has to defend against an ANDROID device carrying a browser subscription.
const PLATFORM_CHANNEL: Readonly<Record<DevicePlatform, NotificationChannel>> = {
  ANDROID: 'EXPO',
  WEB: 'WEB_PUSH',
};

// No `userId` field, by design: the user is derived from the verified Firebase token, never from
// the body (docs/system-design.md §13).
export const RegisterDeviceRequestSchema = z
  .strictObject({
    installationId: InstallationIdSchema,
    platform: DevicePlatformSchema,
    credential: DeviceCredentialSchema,
  })
  .superRefine((value, context) => {
    const expected = PLATFORM_CHANNEL[value.platform];
    if (value.credential.kind !== expected) {
      context.addIssue({
        code: 'custom',
        path: ['credential', 'kind'],
        message: `A ${value.platform} device must register a ${expected} credential`,
      });
    }
  });

// Deliberately has no credential field. The stored token/subscription is encrypted at rest and
// must never leave the API, so the response type makes returning it impossible rather than
// relying on every call site to remember to strip it (ADR 0012).
export const DeviceInstallationSchema = z.strictObject({
  id: UuidSchema,
  installationId: InstallationIdSchema,
  platform: DevicePlatformSchema,
  channel: NotificationChannelSchema,
  lastSeenAt: IsoDateTimeSchema,
  createdAt: IsoDateTimeSchema,
  updatedAt: IsoDateTimeSchema,
});

export const RegisterDeviceResponseSchema = z.strictObject({
  device: DeviceInstallationSchema,
});

// The VAPID public key is served by the API rather than shipped as a build-time variable so that
// key and adapter always come from the same source; the private half never leaves the server.
export const VapidPublicKeyResponseSchema = z.strictObject({
  publicKey: WebPushKeySchema,
});

// Aggregate counters only — no occurrence ids, amounts, credentials or provider messages, so the
// response is safe to log (docs/system-design.md §13).
export const DispatchNotificationsResponseSchema = z.strictObject({
  claimed: z.int().nonnegative(),
  sent: z.int().nonnegative(),
  failed: z.int().nonnegative(),
  // False when another dispatch for this household already held the advisory lock, in which case
  // the counters are all zero and this call did nothing.
  skipped: z.boolean(),
});

export type DevicePlatform = z.infer<typeof DevicePlatformSchema>;
export type NotificationChannel = z.infer<typeof NotificationChannelSchema>;
export type NotificationDeliveryStatus = z.infer<typeof NotificationDeliveryStatusSchema>;
export type DeviceCredential = z.infer<typeof DeviceCredentialSchema>;
export type RegisterDeviceRequest = z.infer<typeof RegisterDeviceRequestSchema>;
export type RegisterDeviceResponse = z.infer<typeof RegisterDeviceResponseSchema>;
export type DeviceInstallation = z.infer<typeof DeviceInstallationSchema>;
export type VapidPublicKeyResponse = z.infer<typeof VapidPublicKeyResponseSchema>;
export type DispatchNotificationsResponse = z.infer<typeof DispatchNotificationsResponseSchema>;
